workflows:
  main:
    name: 'Build and test'
    environment:
      vars:
        SOLUTION: '**/*.sln'
        BUILD_PLATFORM: 'Any CPU'
        BUILD_CONFIGURATION: 'Release'
    scripts:
    - name: Install .NET MAUI
      script: |
        sudo installer -pkg https://aka.ms/dotnet-maui/sdk/Preview3/dotnet-maui-sdk-6.0.100-preview.3.21202.5-macos-x64.pkg -target /
      - name: 'Change Directory'
        script: 'cd /Users/builder/clone'
      - name: 'Restore NuGet packages'
        script: 'dotnet restore $SOLUTION'
      - name: 'Build Android'
        script: 'msbuild /t:PackageForAndroid /p:Configuration=$BUILD_CONFIGURATION $SOLUTION'
      - name: 'Build iOS'
        script: 'msbuild /t:Build /p:Platform=iPhone /p:OutputPath=$BITRISE_DEPLOY_DIR/iOS $SOLUTION'
      - name: 'Build Mac Catalyst'
        script: 'msbuild /t:Build /p:OutputPath=$BITRISE_DEPLOY_DIR/MacCatalyst $SOLUTION'
      - name: 'Test iOS'
        script: 'msbuild /t:RunTests /p:Platform=iPhone /p:OutputPath=$BITRISE_DEPLOY_DIR/iOS $SOLUTION'
      - name: 'Test Mac Catalyst'
        script: 'msbuild /t:RunTests /p:OutputPath=$BITRISE_DEPLOY_DIR/MacCatalyst $SOLUTION'
